import StyleV4 from './v4Style';
import Event from './event';

export default class AssBuilder {
  title = '';
  playResX = 0;
  playResY = 0;
  scriptType = 'v4.00+';
  scaledBorderAndShadow = 'yes';
  styles: Array<StyleV4> = [];
  events: Array<Event> = [];

  constructor(title: string = '', playResX: number, playResY: number) {
    this.title = title;
    this.playResX = playResX;
    this.playResY = playResY;
  }

  public addStyle(style: StyleV4) {
    this.styles.push(style);
  }

  public addEvent(event: Event) {
    this.events.push(event);
  }

  public getStyleCount(): number {
    return this.styles.length;
  }

  public build(): string {
    let content = `[Script Info]
; Script generated by Syndicate
Title: ${this.title}
ScriptType: ${this.scriptType}
PlayResX: ${this.playResX}
PlayResY: ${this.playResY}
ScaledBorderAndShadow: ${this.scaledBorderAndShadow}
`;

    content += StyleV4.definitionString();
    for (let i = 0; i < this.styles.length; i++) {
      content += this.styles[i].toString();
    }

    content += Event.definitionString();
    for (let i = 0; i < this.events.length; i++) {
      content += this.events[i].toString();
    }

    return content;
  }
}
